### ISSUE TITLE
Ability to interact using group chats

### ISSUE THREAD

**Issue by amravyan** [MikeSafonov/jenkins-telegram-chatops#12]
Hello.
I'm not sure, but I couldn't get answers from the bot in a group chat. I've tried to add group chat id (with and without minus) at telegram.bot.users property.
Could yuo please check if it should work.
If no, are you planning to add this feature?

**Comment by MikeSafonov** [comment]
Greetings!
First of all, you need to verify your bot able to join groups (BotFather -> /setjoingroups -> YourBotName -> ENABLED).
Then, add group id to telegram.bot.users property and add your bot to group.

Unfortunately bot reacting only on commands starting with `/`  and ignore `/<command>@<botname`.
I plan to fix this soon.
